### ISSUE TITLE
several improvements for xirsys p2p lib

### ISSUE THREAD

**Issue by mythicallage** [xirsys/xirsys-examples-v3#4]
Hello.

I would like to share several improvements.

1. [xirsys.p2p.adapter.js](https://github.com/xirsys/xirsys-examples-v3/blob/master/app/public/lib/xirsys.p2p.adapter.js)

It is for Chrome. reattachMediaStream function must be as down below:
```
reattachMediaStream = function (to, from) {
	if (typeof from.srcObject !== 'undefined') {
		to.srcObject = from.srcObject;
	} else if (typeof from.mozSrcObject !== 'undefined') {
		to.mozSrcObject = from.mozSrcObject;
	} else if (typeof from.src !== 'undefined') {
		to.src = from.src;
	}
};
```

2. [xirsys.p2p.js](https://github.com/xirsys/xirsys-examples-v3/blob/master/app/public/lib/xirsys.p2p.js)
Sometimes onUserMediaSuccess  event would be useful.
It needs to add event onUserMediaSuccess in the list below:
```
statics : {
	/* status */
	...
	/* events */
	offer : "p2p.offer",
	answer : "p2p.answer",
	error : "p2p.error",
	onUserMediaSuccess: "p2p.onUserMediaSuccess",
	...
```
Then we should change onUserMediaSuccess function as down below:
```
	onUserMediaSuccess : function ($stream) {
		if (!!this.rtc.localVideo && this.rtc.useVideo) {
			attachMediaStream(this.rtc.localVideo, $stream);
			this.rtc.localStream = $stream;
		}
		$xirsys.events.getInstance().emit($xirsys.p2p.onUserMediaSuccess);
	},
```

Thank you.

**Comment by jerrychabolla** [comment]
Brilliant.  Thanks for the suggestions.  Were about to do an update with our examples, we'll be sure to add your suggestions as we modify our sources.  Many Thanks!
