### ISSUE TITLE
Audio is not being transferred in webrtc_chat 

### ISSUE THREAD

**Issue by pzimn** [xirsys/xirsys-examples-v3#5]
Hello, I wanted to try out few of yours examples. 
Considering first app example - called webrtc_chat, everything works like a charm apart from audio(voice) transfer between two peers. 
The video stream seems okey but unfortunately without audio.

**Comment by noeplease** [comment]
Seems like an update, to allow autoplay without a user gesture for Safari on iOS, caused the audio to be muted by default. We added simple handling to unmute the remote video's audio, when the onplaying event fired.

Please pull again and let us know if the latest update works out.
